### ISSUE TITLE
I can't install pytest-dependency in a single pass with requirements.txt

### ISSUE THREAD

**Issue by matthewcummings** [RKrahl/pytest-dependency#14] opened 2017-11-20 12:57 UTC
This module is great, it's helped me out quite a bit with some complicated test dependencies that I have.

However, I cannot pip install it via requirements.txt. When I do, I see an error that pytest is not installed, even when I specify pytest before pytest-dependency.

I found a workaround: install all other dependencies via pip install -r requirements.txt, then run pip install pytest-dependency. The doc states that you should download and unpack the source and use setup.py.

I would rather use pip though. I am using a virtualenv. Just wondering what I'm doing wrong with the first approach or why I'm seeing this error.  Is there a specific reason why pip is not officially supported or is that just a doc issue?

Thanks!

**Comment by RKrahl** [comment] 2017-11-20 22:20
So it seem to be a duplicate of #13 then.  Please not that there are still a [few things that I plan to get done for the next release](https://github.com/RKrahl/pytest-dependency/milestone/3).

**Closed by RKrahl** 2017-11-20 22:20 UTC
Labels: duplicate
